import {mountPdfWorkflow} from './pdf-workflow.js';
import {firebaseConfig} from './firebase-config.js';
import {today,roomNumber,buildings,parseCSV,buildRoster,csvString} from './domain.js';
import {demoStore,firebaseStore} from './store.js';
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>(Number(n||0)/100).toLocaleString('th-TH',{style:'currency',currency:'THB'});
const time=t=>{if(!t)return 'กำลังยืนยัน';const d=t.toDate?t.toDate():new Date(t);return d.toLocaleTimeString('th-TH',{timeZone:'Asia/Bangkok',hour:'2-digit',minute:'2-digit',second:'2-digit'});};
const sortEvents=events=>[...events].sort((a,b)=>{const n=x=>x?.toMillis?x.toMillis():new Date(x||0).getTime();return n(b.createdAt)-n(a.createdAt);});
let store,authClient,serviceDate=today(),currentState={day:null,counts:{},events:[],fresh:false},historyState={events:[]},selected=null,rows=[],importRooms=null,expectedVersion=null,previewDate=null,importGeneration=0,busy=false,page='check',unwatch=()=>{},unhistory=()=>{},toastTimer;
function message(text,error=false){$('#message').textContent=text;$('#message').className=error?'error':'';$('#message').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#message').hidden=true,error?12000:5000);}
function errorMessage(e){console.error(e.code||e.message);const messages={'permission-denied':'ไม่มีสิทธิ์เข้าถึงข้อมูล กรุณาตรวจบัญชีและ Firestore Rules','auth/invalid-credential':'อีเมลหรือรหัสผ่านไม่ถูกต้อง','auth/too-many-requests':'มีการลองเข้าสู่ระบบหลายครั้ง กรุณารอสักครู่','auth/network-request-failed':'เชื่อมต่อ Firebase ไม่ได้ กรุณาตรวจอินเทอร์เน็ต','unavailable':'เชื่อมต่อฐานข้อมูลไม่ได้ กรุณาลองใหม่','auth/invalid-api-key':'Firebase API key ไม่ถูกต้อง กรุณาตรวจ firebase-config.js'};return messages[e.code]||e.message||'เกิดข้อผิดพลาด กรุณาลองใหม่';}
function failure(e){message(errorMessage(e),true);}
function connection(){const online=navigator.onLine;$('#connection').textContent=store?.demo?'โหมดทดลอง':!online?'ออฟไลน์ · หยุดบันทึก':store?(currentState.fresh?'เชื่อมต่อแล้ว':'กำลังซิงก์'):'ยังไม่เข้าสู่ระบบ';$('#banner').hidden=online&&!store?.demo;$('#banner').textContent=store?.demo?'โหมดทดลอง · ข้อมูลสมมติอยู่ในแท็บนี้ ไม่ส่งไป Firebase':!online?'อินเทอร์เน็ตขาดหาย กรุณารอเชื่อมต่อก่อนบันทึก':'';if($('#save-entry')){$('#save-entry').disabled=busy||(!store.demo&&(!online||!currentState.fresh));$('#save-entry').textContent=busy?'กำลังบันทึก…':selected?.expected.pkg==='RO'?'รับเงินแล้ว · ยืนยันเข้าทาน':'ยืนยันเข้าทาน';}$('#room').disabled=busy;document.querySelectorAll('#room-keypad button,[data-building],#search-room').forEach(b=>b.disabled=busy);document.querySelectorAll('#entry-form input,#entry-form select,#entry-form button:not(#save-entry)').forEach(b=>b.disabled=busy);if(!busy&&$('#pax')){const n=Number($('#pax').value);$('#pax-minus').disabled=n<=1;$('#pax-plus').disabled=n>=Number($('#pax').max);}}
function requireOnline(){if(!store?.demo&&!navigator.onLine)throw new Error('กรุณาเชื่อมต่ออินเทอร์เน็ตก่อนบันทึก');}
function clearGuest(){selected=null;$('#guest').innerHTML='<div class="guest-wait"><div class="waiting-number">— — — —</div><h2>รอเลขห้อง</h2><p>กรอกครบ 4 หลัก ระบบจะแสดงชื่อ<br>สิทธิ์อาหารเช้า และจำนวนผู้พัก</p></div>';}
function activate(s){document.body.classList.remove('reception-focus');$('#focus-mode').setAttribute('aria-pressed','false');$('#focus-mode').textContent='โหมดรับลูกค้า';$('#last-success').hidden=true;$('#room').value='';updateRoomDescription();unwatch();unhistory();store=s;clearGuest();currentState={day:null,counts:{},events:[],fresh:false};$('#gate').hidden=!!s;$('#workspace').hidden=!s;$('#logout').hidden=!s;$('#account').textContent=s?s.user.email+' · '+s.user.role:'';if(!s){connection();return;}$('#admin-only').hidden=s.user.role==='admin';$('#import-controls').hidden=s.user.role!=='admin';serviceDate=today();$('#import-date').value=serviceDate;$('#pdf-date').value=serviceDate;$('#history-date').value=serviceDate;document.dispatchEvent(new Event('laya-session-change'));subscribe();connection();}
function subscribe(){unwatch();unhistory();$('#service-date').textContent=serviceDate;unwatch=store.watch(serviceDate,state=>{currentState=state;renderDaily();if($('#history-date').value===serviceDate){historyState=state;renderHistory();}connection();},failure);watchHistory();}
function watchHistory(){unhistory();historyState={events:[]};renderHistory();if(store&&$('#history-date').value===serviceDate){historyState=currentState;renderHistory();}else if(store&&$('#history-date').value)unhistory=store.watch($('#history-date').value,state=>{historyState=state;renderHistory();},failure);}
function renderDaily(){const d=currentState.day,events=currentState.events;$('#roster-status').textContent=d?Object.keys(d.rooms).length+' ห้อง · ข้อมูลวันนี้':'ยังไม่มีรายงานของวันนี้';$('#total').textContent=events.reduce((s,e)=>s+e.pax,0);for(const pkg of ['RB','RO'])$('#'+pkg.toLowerCase()+'-total').textContent=events.filter(e=>e.pkg===pkg).reduce((s,e)=>s+e.pax,0)+' คน';$('#revenue').textContent=money(events.reduce((s,e)=>s+e.amount,0));$('#recent').className=events.length?'':'empty';$('#recent').innerHTML=events.length?sortEvents(events).slice(0,7).map(e=>'<div class="entry"><div><strong>'+esc(e.room)+' · '+e.pax+' คน</strong><small>'+e.pkg+' · '+(e.pkg==='RO'?'ชำระ '+money(e.amount):'รวมอาหารเช้า')+'</small></div><div class="entry-right"><small>'+time(e.createdAt)+'</small><small>ตึก '+buildings[e.room[0]]+'</small></div></div>').join(''):'ยังไม่มีรายการ';if(selected){const count=currentState.counts[selected.room]?.count||0;const el=$('#live-count');if(el)el.textContent=count;const remaining=$('#live-remaining');if(remaining)remaining.textContent=Math.max(0,(currentState.day?.rooms[selected.room]?.pax||0)-count);}}
function findRoom(){
 if(busy)return;rollover();clearGuest();
 try{
  if(!currentState.day)throw new Error('ยังไม่มีรายงานของวันนี้ กรุณาให้ผู้ดูแลนำเข้าข้อมูลก่อน');
  if(!store.demo&&!currentState.fresh)throw new Error('กำลังรอข้อมูลล่าสุด กรุณาตรวจอินเทอร์เน็ต');
  const room=roomNumber($('#room').value);$('#room').value=room;updateRoomDescription();
  const r=currentState.day.rooms[room];if(!r)throw new Error('ไม่พบห้อง '+room+' ในรายงานวันนี้ กรุณาตรวจสอบกับ Front Office');
  if(!['RO','RB'].includes(r.pkg)){
   $('#guest').innerHTML='<div class="guest-state hold"><span class="state-label">รอตรวจสอบกับ FO</span><div class="guest-room">'+room+'</div><p>ยังไม่ยืนยันสิทธิ์หรือจำนวนผู้พัก</p></div><div class="names">'+r.names.map(esc).join('<br>')+'</div><div class="notice">ให้ผู้ดูแลตรวจรายงานก่อนบันทึกเข้าทาน</div>';return;
  }
  selected={room,expected:structuredClone(r),id:crypto.randomUUID()};
  const count=currentState.counts[room]?.count||0,remaining=Math.max(0,r.pax-count);
  $('#guest').innerHTML='<div class="guest-state '+(r.pkg==='RO'?'payment':'included')+'"><div class="guest-state-top"><span class="state-label">'+(r.pkg==='RO'?'RO · ต้องชำระเงิน':'RB · รวมอาหารเช้า')+'</span><span>ตึก '+buildings[room[0]]+' · ชั้น '+room[1]+'</span></div><div class="guest-room">'+room+'</div><p>'+(r.pkg==='RO'?'รับชำระก่อนยืนยันเข้าทาน':'ทานอาหารเช้าได้โดยไม่ต้องชำระเพิ่ม')+'</p></div><div class="names">'+r.names.map(esc).join('<br>')+'</div><div class="occupancy"><div><small>ผู้พักทั้งหมด</small><strong>'+r.pax+' คน</strong></div><div><small>เข้าทานแล้ว</small><strong><span id="live-count">'+count+'</span> คน</strong></div><div><small>คงเหลือ</small><strong><span id="live-remaining">'+remaining+'</span> คน</strong></div></div>'+
  (remaining===0?'<div class="notice">บันทึกครบจำนวนผู้พักแล้ว กรุณาตรวจสอบกับ FO</div>':'<form id="entry-form"><label for="pax">มาทานรอบนี้กี่คน?</label><div class="pax-stepper"><button type="button" id="pax-minus" aria-label="ลดจำนวนคน">−</button><input id="pax" type="number" min="1" max="'+remaining+'" step="1" required value="1" aria-describedby="pax-hint"><button type="button" id="pax-plus" aria-label="เพิ่มจำนวนคน">+</button></div><div class="pax-quick">'+Array.from({length:Math.min(3,remaining)},(_,i)=>'<button type="button" data-pax="'+(i+1)+'" aria-pressed="'+(i===0)+'">'+(i+1)+' คน</button>').join('')+(remaining>3?'<button type="button" data-pax="'+remaining+'" aria-pressed="false">มาครบ '+remaining+' คน</button>':'')+'</div><small id="pax-hint" class="hint">เลือกจำนวนคนที่มารอบนี้ บันทึกเพิ่มภายหลังได้</small>'+
  (r.pkg==='RO'?'<div class="payment-fields"><div class="form-grid"><label>ยอดรับชำระรวม (บาท)<input id="amount" type="number" inputmode="decimal" min="0.01" max="1000000" step="0.01" placeholder="0.00" required></label><label>วิธีชำระ<select id="method"><option value="cash">เงินสด</option><option value="card">บัตรเครดิต</option><option value="transfer">โอนเงิน</option></select></label></div><label class="paid-check"><input id="paid" type="checkbox" required><span>ได้รับชำระเงินเรียบร้อยแล้ว</span></label></div>':'')+
  '<button id="save-entry" class="primary full '+(r.pkg==='RO'?'save-paid':'save-rb')+'">'+(r.pkg==='RO'?'รับเงินแล้ว · ยืนยันเข้าทาน':'ยืนยันเข้าทาน')+'</button></form>');
  $('#entry-form')?.addEventListener('submit',saveEntry);
  if($('#pax')){
   const sync=()=>{const n=Number($('#pax').value);document.querySelectorAll('[data-pax]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.pax)===n)));$('#pax-minus').disabled=busy||n<=1;$('#pax-plus').disabled=busy||n>=remaining;};
   $('#pax-minus').addEventListener('click',()=>{$('#pax').value=Math.max(1,(Number($('#pax').value)||1)-1);sync();});
   $('#pax-plus').addEventListener('click',()=>{$('#pax').value=Math.min(remaining,(Number($('#pax').value)||1)+1);sync();});
   document.querySelectorAll('[data-pax]').forEach(b=>b.addEventListener('click',()=>{$('#pax').value=b.dataset.pax;sync();}));$('#pax').addEventListener('input',sync);sync();
  }
  connection();
 }catch(e){$('#guest').innerHTML='<div class="guest-state payment" role="alert"><span class="state-label">ตรวจสอบเลขห้อง</span><p>'+esc(errorMessage(e))+'</p></div>';}
}
function updateRoomDescription(){
 const value=$('#room').value.toUpperCase();let text='กด 4 หลัก หรือพิมพ์แล้ว Enter';
 try{if(value.length===4){const room=roomNumber(value);text='ตึก '+buildings[room[0]]+' · ชั้น '+room[1]+' · ห้อง '+room.slice(2);}else if(buildings[value[0]])text='ตึก '+buildings[value[0]]+' · ใส่เลขที่เหลือ';}catch{text='รับเฉพาะตึก 1, 2, 3, 5 หรือ A, B, C, D';}
 $('#room-description').textContent=text;
 document.querySelectorAll('[data-building]').forEach(b=>b.setAttribute('aria-pressed',String(value[0]===b.dataset.building)));
}
function roomInputChanged(){if(busy)return;clearGuest();$('#last-success').hidden=true;updateRoomDescription();if($('#room').value.length===4)findRoom();}
function editRoom(value){if(busy)return;$('#room').value=value;roomInputChanged();if(value.length===4&&matchMedia('(max-width: 760px)').matches)$('.guest-panel').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}
function initReception(){
 document.querySelectorAll('[data-digit]').forEach(b=>b.addEventListener('click',()=>{const raw=$('#room').value;editRoom((raw.length>=4?'':raw)+b.dataset.digit);}));
 document.querySelectorAll('[data-building]').forEach(b=>b.addEventListener('click',()=>editRoom(b.dataset.building)));
 $('#clear-room').addEventListener('click',()=>editRoom(''));$('#backspace-room').addEventListener('click',()=>editRoom($('#room').value.slice(0,-1)));
 $('#focus-mode').addEventListener('click',()=>{const active=document.body.classList.toggle('reception-focus');$('#focus-mode').setAttribute('aria-pressed',String(active));$('#focus-mode').textContent=active?'กลับเมนูหลัก':'โหมดรับลูกค้า';});
}
async function saveEntry(e){e.preventDefault();if(busy||!selected)return;busy=true;connection();const request={...selected};try{requireOnline();if(serviceDate!==today())throw new Error('เปลี่ยนวันแล้ว กรุณาค้นหาใหม่');const pax=Number($('#pax').value),amount=request.expected.pkg==='RO'?Math.round(Number($('#amount').value)*100):0,method=request.expected.pkg==='RO'?$('#method').value:'';await store.checkin(serviceDate,request.room,pax,amount,method,request.id,request.expected);$('#message').hidden=true;clearTimeout(toastTimer);busy=false;clearGuest();connection();$('#room').value='';updateRoomDescription();$('#last-success').textContent='✓ ห้อง '+request.room+' · บันทึก '+pax+' คนแล้ว — พร้อมรับห้องถัดไป';$('#last-success').hidden=false;if(matchMedia('(pointer: fine)').matches)$('#room').focus({preventScroll:true});else{$('#room').blur();$('.search-panel').scrollIntoView({behavior:'instant',block:'start'});}}catch(err){failure(err);}finally{busy=false;connection();}}
function filtered(){return sortEvents(historyState.events).filter(e=>!$('#building-filter').value||buildings[e.room[0]]===$('#building-filter').value);}
function renderHistory(){const events=filtered();$('#history-summary').innerHTML='<strong>รวม '+events.reduce((s,e)=>s+e.pax,0)+' คน</strong><span>RB '+events.filter(e=>e.pkg==='RB').reduce((s,e)=>s+e.pax,0)+' คน</span><span>RO '+events.filter(e=>e.pkg==='RO').reduce((s,e)=>s+e.pax,0)+' คน</span><span>รับชำระ '+money(events.reduce((s,e)=>s+e.amount,0))+'</span>';$('#history-body').innerHTML=events.map(e=>'<tr><td>'+time(e.createdAt)+'</td><td>'+esc(e.room)+' / '+buildings[e.room[0]]+'</td><td>'+e.names.map(esc).join('<br>')+'</td><td>'+e.pax+'</td><td>'+esc(e.pkg)+'</td><td>'+money(e.amount)+'</td><td>'+esc(e.staffEmail)+'</td></tr>').join('')||'<tr><td colspan="7" class="empty">ไม่พบรายการในวันที่เลือก</td></tr>';}
function invalidateImport(){importGeneration++;previewDate=null;importRooms=null;$('#commit-import').hidden=true;$('#import-preview').textContent='';}
function mappingUI(){invalidateImport();$('#mapping').hidden=false;const headers=rows[0];const aliases={room:/^(room|room\s*(no\.?|number)|เลขห้อง|ห้อง)$/i,name:/^(guest\s*name|name|ชื่อแขก|ชื่อ|ชื่อผู้พัก)$/i,pax:/^(pax|guests|adults|จำนวนผู้พัก|จำนวน|ผู้พัก)$/i,pkg:/^(package|meal\s*plan|rate\s*code|แพ็กเกจ|แพคเกจ|สถานะ)$/i};$('#map-fields').innerHTML=Object.entries({room:'เลขห้อง',name:'ชื่อแขก',pax:'จำนวนผู้พัก',pkg:'RO / RB'}).map(([key,label])=>{const match=headers.findIndex(h=>aliases[key].test(String(h).trim()));return '<label>'+label+'<select id="map-'+key+'"><option value="">— เลือกคอลัมน์ —</option>'+headers.map((h,i)=>'<option value="'+i+'" '+(i===match?'selected':'')+'>'+esc(h||'คอลัมน์ '+(i+1))+'</option>').join('')+'</select></label>';}).join('');$('#map-fields').querySelectorAll('select').forEach(x=>x.addEventListener('change',invalidateImport));}
let xlsxPromise;
async function loadXlsx(){if(window.XLSX)return window.XLSX;if(!xlsxPromise)xlsxPromise=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=new URL('./vendor/xlsx.full.min.js',import.meta.url).href;script.onload=()=>resolve(window.XLSX);script.onerror=()=>{xlsxPromise=null;reject(new Error('โหลดตัวอ่าน Excel ไม่สำเร็จ กรุณาบันทึกเป็น CSV UTF-8 แล้วลองอีกครั้ง'));};document.head.append(script);});return xlsxPromise;}
$('#file').addEventListener('change',async e=>{invalidateImport();rows=[];$('#mapping').hidden=true;const file=e.target.files[0];const generation=importGeneration;if(!file)return;let loadedRows;try{if(file.size>5*1024*1024)throw new Error('ไฟล์ต้องไม่เกิน 5 MB');if(/\.(csv|tsv)$/i.test(file.name))loadedRows=parseCSV(await file.text());else if(/\.xlsx?$/i.test(file.name)){const X=await loadXlsx();const wb=X.read(await file.arrayBuffer(),{type:'array'});loadedRows=X.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{header:1,defval:'',raw:false,blankrows:false});}else throw new Error('รองรับ CSV / TSV / XLSX / XLS เท่านั้น');if(generation!==importGeneration)return;rows=loadedRows;if(rows.length<2)throw new Error('ไฟล์ต้องมีหัวคอลัมน์และข้อมูลอย่างน้อยหนึ่งแถว');mappingUI();}catch(err){failure(err);}});
$('#preview').addEventListener('click',async()=>{invalidateImport();const generation=importGeneration;try{requireOnline();const date=$('#import-date').value;if(!date)throw new Error('กรุณาเลือกวันที่');const mode=$('#row-mode').value,map={};for(const key of ['room','name','pax','pkg']){const v=$('#map-'+key).value;if(v===''&&(key!=='pax'||mode==='room'))throw new Error('กรุณาเลือกคอลัมน์ให้ครบ');map[key]=Number(v);}const keys=mode==='room'?['room','name','pax','pkg']:['room','name','pkg'];if(new Set(keys.map(k=>map[k])).size!==keys.length)throw new Error('กรุณาเลือกคอลัมน์แต่ละประเภทไม่ซ้ำกัน');const result=buildRoster(rows,map,mode);if(!Object.keys(result.rooms).length&&!result.errors.length)throw new Error('ไม่พบห้องที่นำเข้าได้');if(result.errors.length){$('#import-preview').innerHTML='<div class="error">พบ '+result.errors.length+' จุดที่ต้องแก้ก่อนนำเข้า\n'+result.errors.slice(0,30).map(esc).join('\n')+'</div>';return;}const old=await store.getDay(date);if(generation!==importGeneration)return;previewDate=date;expectedVersion=old?.version||null;importRooms=result.rooms;const values=Object.values(importRooms);$('#import-preview').innerHTML='<div class="preview-count success">ห้องพักที่นำเข้า '+values.length+' ห้อง · ผู้พัก '+values.reduce((s,r)=>s+r.pax,0)+' คน</div>'+(result.skipped.length?'<div class="notice">ตัดห้องที่ไม่ใช่ตึก A–D ออก '+result.skipped.length+' แถว (ไม่รวมในจำนวนห้องและผู้พัก)'+(result.skipped.length<=15?'<br>'+result.skipped.map(x=>'แถว '+x.row+': '+esc(x.room)).join(', '):'')+'</div>':'')+(old?'<div class="notice">มีข้อมูลวันที่ '+esc(date)+' อยู่แล้ว การยืนยันจะแทนที่รายชื่อผู้พักของวันนี้ โดยคงประวัติการเข้าทานทั้งหมดไว้ ห้องที่หายไปจะค้นหาไม่ได้</div>':'')+'<div class="table-wrap"><table><thead><tr><th>ห้อง</th><th>ชื่อ</th><th>คน</th><th>สิทธิ์</th></tr></thead><tbody>'+values.slice(0,20).map(r=>'<tr><td>'+r.room+'</td><td>'+r.names.map(esc).join('<br>')+'</td><td>'+r.pax+'</td><td>'+r.pkg+'</td></tr>').join('')+'</tbody></table></div><p class="hint">แสดงตัวอย่างสูงสุด 20 ห้อง · วันที่นำเข้า '+esc(date)+'</p>';$('#commit-import').hidden=false;}catch(e){failure(e);}});
$('#commit-import').addEventListener('click',async()=>{if(!importRooms)return;const b=$('#commit-import');b.disabled=true;try{requireOnline();const date=previewDate,roomsToSave=importRooms,versionToSave=expectedVersion;if(!date||!roomsToSave)return;if(!confirm('ยืนยันนำเข้าข้อมูล '+Object.keys(roomsToSave).length+' ห้อง สำหรับวันที่ '+date+'?'))return;await store.importDay(date,roomsToSave,versionToSave);message('นำเข้าข้อมูลสำเร็จ');invalidateImport();clearGuest();}catch(e){failure(e);}finally{b.disabled=false;}});
for(const id of ['import-date','row-mode'])$('#'+id).addEventListener('change',invalidateImport);
$('#search').addEventListener('submit',e=>{e.preventDefault();findRoom();});$('#room').addEventListener('input',roomInputChanged);initReception();
$('#history-date').addEventListener('change',watchHistory);$('#building-filter').addEventListener('change',renderHistory);
$('#export').addEventListener('click',()=>{const data=[['Date','Time (Bangkok)','Room','Building','Guest Names','Pax','Package','Amount THB','Method','Staff'],...filtered().map(e=>[$('#history-date').value,time(e.createdAt),e.room,buildings[e.room[0]],e.names.join(' / '),e.pax,e.pkg,(e.amount/100).toFixed(2),e.method,e.staffEmail])];const url=URL.createObjectURL(new Blob([csvString(data)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Breakfast_'+$('#history-date').value+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>{page=b.dataset.page;document.querySelectorAll('[data-page]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));for(const p of ['check','import','history'])$('#page-'+p).hidden=p!==page;}));
$('#demo').addEventListener('click',()=>activate(demoStore()));$('#logout').addEventListener('click',async()=>{try{await store.logout();activate(null);}catch(e){failure(e);}});
$('#login').addEventListener('submit',async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;$('#gate-error').textContent='';try{await authClient.login($('#email').value.trim(),$('#password').value);$('#password').value='';}catch(err){$('#gate-error').textContent=errorMessage(err);}finally{b.disabled=false;}});
function rollover(){if(store&&serviceDate!==today()){serviceDate=today();clearGuest();$('#room').value='';$('#history-date').value=serviceDate;$('#import-date').value=serviceDate;invalidateImport();currentState={day:null,counts:{},events:[],fresh:false};subscribe();message('เปลี่ยนวันบริการแล้ว กรุณาตรวจรายงานของวันนี้');}}
window.addEventListener('online',connection);window.addEventListener('offline',connection);document.addEventListener('visibilitychange',()=>{rollover();connection();});setInterval(rollover,15000);
mountPdfWorkflow({getStore:()=>store,notify:message,onImported:()=>{clearGuest();invalidateImport();}});
const configured=['apiKey','authDomain','projectId','appId'].every(k=>firebaseConfig[k]);$('#setup').hidden=configured;$('#login').hidden=!configured;connection();if(configured){try{authClient=await firebaseStore(firebaseConfig,s=>{if(!store?.demo)activate(s);},e=>{$('#gate-error').textContent=errorMessage(e);failure(e);});}catch(e){$('#gate-error').textContent='เริ่ม Firebase ไม่สำเร็จ: '+errorMessage(e);}}
