import {today,validateEntry,makeWalkinEvent} from './domain.js';
export function demoStore(){
  let rateRules={mapping:{},version:null};let data={};try{data=JSON.parse(sessionStorage.getItem('laya-breakfast-demo-v1')||'{}');}catch{}
  const d=today();if(!data[d])data[d]={day:{version:'demo',uploadedBy:'demo',rooms:{'1101':{room:'1101',names:['Anna Wilson'],pax:2,pkg:'RB'},'2203':{room:'2203',names:['Li Wei'],pax:3,pkg:'RO'},'5102':{room:'5102',names:['Alex Ivanov'],pax:2,pkg:'RB'}}},counts:{},events:[]};
  const listeners=new Set();const persist=()=>{sessionStorage.setItem('laya-breakfast-demo-v1',JSON.stringify(data));listeners.forEach(f=>f());};
  return {user:{uid:'demo',email:'demo@laya.local',role:'admin'},demo:true,
    watch(date,cb){const f=()=>{const x=data[date]||{};cb({day:x.day||null,counts:x.counts||{},events:x.events||[],fresh:true});};listeners.add(f);f();return()=>listeners.delete(f);},
    async importDay(date,rooms,version){const x=data[date]||{counts:{},events:[]};if((x.day?.version||null)!==version)throw new Error('มีการอัปโหลดข้อมูลใหม่จากเครื่องอื่น กรุณาตรวจใหม่');x.day={rooms,version:crypto.randomUUID(),uploadedBy:'demo',uploadedAt:new Date().toISOString()};data[date]=x;persist();},
    async checkin(date,room,pax,amount,method,id,expected,payment=null){if(date!==today())throw new Error('เปลี่ยนวันแล้ว กรุณาค้นหาใหม่');const x=data[date];if(x.events.some(e=>e.id===id))return;const r=x?.day?.rooms[room];if(JSON.stringify(r)!==JSON.stringify(expected))throw new Error('ข้อมูลห้องเปลี่ยน กรุณาค้นหาใหม่');const count=x.counts[room]?.count||0;validateEntry(r,count,pax,amount,method,payment?.status||'paid',payment?.dueAmount||0);x.counts[room]={count:count+pax};x.events.push({id,room,names:r.names,pkg:r.pkg,pax,amount,method,staffEmail:'demo@laya.local',createdAt:new Date().toISOString(),...(payment?{paymentStatus:payment.status,dueAmount:payment.dueAmount}:{} )});persist();},
    async walkin(date,input){if(date!==today())throw new Error('เปลี่ยนวันแล้ว');const event=makeWalkinEvent(input,'demo@laya.local'),x=data[date]??={day:{rooms:{},version:crypto.randomUUID(),walkinOnly:true},counts:{},events:[]};if(x.events.some(e=>e.id===event.id))return;x.events.push(event);persist();},
    async settlePayment(date,id,method){if(!['cash','card','transfer'].includes(method))throw new Error('วิธีรับเงินไม่ถูกต้อง');const e=data[date]?.events.find(e=>e.id===id);if(!e)throw new Error('ไม่พบรายการ');if(e.paymentStatus!=='pending')return;e.amount=e.dueAmount;e.dueAmount=0;e.paymentStatus='paid';e.method=method;e.settledAt=new Date().toISOString();e.settledBy='demo@laya.local';persist();},
    async getRateRules(){return structuredClone(rateRules);},async saveRateRules(mapping,version){if(version!==rateRules.version)throw new Error('มีผู้แก้รหัสใหม่ กรุณาโหลดใหม่');rateRules={mapping,version:crypto.randomUUID()};},async getDay(date){return data[date]?.day||null;},async logout(){}}
}
