import {test} from 'node:test';import assert from 'node:assert/strict';import {mergeReports} from '../pdf-import.js';
const record=(override={})=>({room:'1101',name:'Example Guest',adults:2,children:1,rate:'TEST',arrival:'2026-09-28',departure:'2026-09-30',source:'test.pdf',page:1,evidence:[{kind:'Cashiering',pkg:'RB'}],issues:[],...override});
const report=(records,source='test.pdf')=>({source,records});
test('uses adult/child columns and combines companion names with zero pax',()=>{const r=mergeReports([report([record(),record({name:'Companion',adults:0,children:0,evidence:[]})])],'2026-09-29')['1101'];assert.equal(r.pax,3);assert.equal(r.names.length,2);assert.equal(r.pkg,'RB');});
test('conflicting breakfast evidence is held for review',()=>{const r=mergeReports([report([record({evidence:[{kind:'General',pkg:'RO'},{kind:'Cashiering',pkg:'RB'}]})])],'2026-09-29')['1101'];assert.equal(r.pkg,'REVIEW');});
test('never assigns breakfast from absent evidence; explicit admin mapping can resolve',()=>{const reports=[report([record({rate:'EXACT-BB',evidence:[]})])];assert.equal(mergeReports(reports,'2026-09-29')['1101'].pkg,'REVIEW');assert.equal(mergeReports(reports,'2026-09-29',{'EXACT-BB':'RB'})['1101'].pkg,'RB');});
test('pseudo rooms excluded, zero occupancy held, stale stay held',()=>{const r=mergeReports([report([record({room:'9000'}),record({room:'1102',adults:0,children:0}),record({room:'1103',departure:'2026-09-28'})])],'2026-09-29');assert.equal(r['9000'],undefined);assert.equal(r['1102'].pkg,'REVIEW');assert.equal(r['1103'].pkg,'REVIEW');});
test('duplicate guest rows do not inflate occupancy and remain reviewable',()=>{const r=mergeReports([report([record(),record()])],'2026-09-29')['1101'];assert.equal(r.pax,3);assert.equal(r.pkg,'REVIEW');});

import {packageTags,parseReportPages} from '../pdf-import.js';
test('breakfast tokens allow adjacent pax and split PDF glyphs without matching words/rate codes',()=>{for(const s of ['3RB','2RB','1 RB','Reservation 12RB / HB','rb','R B'])assert.deepEqual(packageTags(s),['RB']);for(const s of ['2RO','RO**ABF OA@350','CL,RO','R O'])assert.deepEqual(packageTags(s),['RO']);for(const s of ['GROUP','TWSRB','OTARO','PRO','AR3RB','RBX'])assert.deepEqual(packageTags(s),[]);assert.deepEqual(packageTags('RO / 2RB'),['RO','RB']);});
const columns={Room:10,Name:45,Company:170,'Arr.':310,'Dep.':365,'Adl.':430,'Chl.':460,Pay:490,Rate:530};
const line=(y,entries)=>entries.map(([text,x])=>({text,x,y,width:15}));
const header=()=>line(100,Object.entries(columns).map(([k,x])=>[k,x]));
const guest=(room,name,y)=>line(y,[[room,10],[name,45],['02/10/26',310],['05/10/26',365],['2',430],['0',460],['CA',490],['UNKNOWN',530]]);
test('reads all room lines, wrapped names and comments continued onto next page without leaking into next room',()=>{
 const pages=[ [...header(),...line(112,[['No.',10]]),...line(124,[['VIP',45],['EDT',365]]),...guest('1101','Guest Long',134),...line(144,[['Name,Mr.',45],['Company continuation',170]]),...line(154,[['Res. Comments: Reservation',90]]),...line(164,[['Long comment before page break',200]]),...line(200,[['Filter',10]])], [...header(),...line(112,[['No.',10]]),...line(124,[['VIP',45],['EDT',365]]),...line(134,[['2RB',200]]),...line(144,[['Second continuation',200]]),...guest('1102','Next Guest',164),...line(174,[['Res. Comments: Cashiering RO',90]]),...line(210,[['Total Rooms',10],['2',300],['4',430],['0',460]])] ];
 const result=parseReportPages(pages,'synthetic.pdf');assert.deepEqual(result.errors,[]);assert.equal(result.records[0].name,'Guest Long Name,Mr.');assert.equal(result.records[0].lines.length,6);assert.equal(result.records[0].evidence[0].pkg,'RB');assert.equal(result.records[0].evidence[0].page,2);assert.deepEqual(result.records[1].evidence.map(x=>x.pkg),['RO']);assert.ok(!result.records[1].lines.some(l=>l.text.includes('2RB')));const rooms=mergeReports([result],'2026-10-03');assert.equal(rooms['1101'].pkg,'RB');assert.equal(rooms['1102'].pkg,'RO');
});
